// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"fmt"
	"testing"

	"github.com/gythialy/magnet/pkg/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.Keyword{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Keyword{}) fail: %s", err)
	}
}

func Test_keywordQuery(t *testing.T) {
	keyword := newKeyword(_gen_test_db)
	keyword = *keyword.As(keyword.TableName())
	_do := keyword.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(keyword.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <keywords> fail:", err)
		return
	}

	_, ok := keyword.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from keyword success")
	}

	err = _do.Create(&model.Keyword{})
	if err != nil {
		t.Error("create item in table <keywords> fail:", err)
	}

	err = _do.Save(&model.Keyword{})
	if err != nil {
		t.Error("create item in table <keywords> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Keyword{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <keywords> fail:", err)
	}

	_, err = _do.Select(keyword.ALL).Take()
	if err != nil {
		t.Error("Take() on table <keywords> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <keywords> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <keywords> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <keywords> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Keyword{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <keywords> fail:", err)
	}

	_, err = _do.Select(keyword.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <keywords> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <keywords> fail:", err)
	}

	_, err = _do.Select(keyword.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <keywords> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <keywords> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <keywords> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <keywords> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Keyword{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <keywords> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <keywords> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <keywords> fail:", err)
	}

	var _a _another
	_aPK := field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <keywords> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <keywords> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <keywords> fail:", err)
	}
}
