// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarm = "alarms"

// Alarm mapped from table <alarms>
type Alarm struct {
	UserID           int64      `gorm:"column:user_id;primaryKey;autoIncrement:false" json:"userId"`
	CreditType       string     `gorm:"column:credit_type;not null" json:"creditType"`
	CreditName       string     `gorm:"column:credit_name;not null" json:"creditName"`
	CreditCode       string     `gorm:"column:credit_code;not null" json:"creditCode"`
	StartDate        time.Time  `gorm:"column:start_date;not null" json:"startDate"`
	EndDate          *time.Time `gorm:"column:end_date" json:"endDate"`
	DetailReason     *string    `gorm:"column:detail_reason" json:"detailReason"`
	HandleDepartment *string    `gorm:"column:handle_department" json:"handleDepartment"`
	HandleUnit       *string    `gorm:"column:handle_unit" json:"handleUnit"`
	HandleResult     *string    `gorm:"column:handle_result" json:"handleResult"`
}

// TableName Alarm's table name
func (*Alarm) TableName() string {
	return TableNameAlarm
}
